// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.2.1_db0@0.3.4_ioredis@5.8.2_magicast@0.5.1_nuxt@4.2.1_@parcel+watc_1ea6eba7234002aaff8d090a1f9db0a7/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.1.0_magicast@0.5.1_vite@7.2.2_@types+node@20.19.24_jiti@2.6.1_lightningcss_ff777ff49a82a8c5a493ff930a629e88/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}