// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_typescript@5.9.3_vue@3.5.24_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_typescript@5.9.3_vue@3.5.24_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@3.1.0_vite@7.2.2_@types+node@20.19.24_jiti@2.6.1_lightningcss@1.30.2_ter_523cc694e0757634747a19f840808fc6/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@3.1.0_vite@7.2.2_@types+node@20.19.24_jiti@2.6.1_lightningcss@1.30.2_ter_523cc694e0757634747a19f840808fc6/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_db0@0.3.4_embla-carousel@8.6.0_ioredis@5.8.2_magica_d4c3c7b013cbc9f2daf96388117ea3b6/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@2.1.0_magicast@0.5.1_vite@7.2.2_@types+node@20.19.24_jiti@2.6.1_lightningcss_ff777ff49a82a8c5a493ff930a629e88/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@20.19.24_@vue+compiler-sfc@3.5.24_db0@0.3._804fcb0806f8d525a87fd02564e8a063/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../plugins/pixi.client")> &
  InjectionType<typeof import("../../plugins/pwa.client")> &
  InjectionType<typeof import("../../plugins/ws.client")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
